### ISSUE TITLE
About providers and other dependencies

### ISSUE THREAD

**Issue by muniter** [nvim-lua/nvim-package-specification#4]
Excited to see the spec :)

Perhaps the spec will benefit by also specifying other type of dependencies:

1. Neovim providers: provider-python, provider-node, etc. This could allow future integration with the healthcheck module.

2. External programs: ripgrep, find, etc. Could also be integrated with the healthcheck module could check for installation by checking for certain executable names, checking version would be perhaps too complex.

Point 1 seems straightforward to do, point 2 is more complex and out of the control of neovim development, still wanted to put the idea out there.

3. The field `description.author` could be a nice addition, I can imagine filtering packages by **tpope**, etc.

**Comment by wbthomason** [comment]
External/system dependencies was brought up by @mjlbach and @lewis6991 and seems like a good thing to add.

**Comment by mjlbach** [comment]
Do you want to split these into separate issues? I think 2 is already covered by https://github.com/nvim-lua/nvim-package-specification/issues/13, I'm not quite sure about 1, maybe an additional key under dependencies `providers?` (cc @ii14). I think 3 is a straightforward addition and could be PR'd

**Comment by mjlbach** [comment]
With authors being added, and https://github.com/nvim-lua/nvim-package-specification/issues/13 for 2, I think the only thing left is 1. Do you want to make a new issue for that?
