### ISSUE TITLE
Naming of specification version

### ISSUE THREAD

**Issue by mjlbach** [nvim-lua/nvim-package-specification#9]
Right now, the name is `specification_version`, ideas:

* `packspec`
* `plugspec`
* `spec`

**Comment by mjlbach** [comment]
I meant the field in the schema, but I think these should be loosely consistent (including repo name)

**Comment by wbthomason** [comment]
I favor `plugspec`, but I also don't have strong feelings about this name.

**Comment by lewis6991** [comment]
For me anything of the form `<something>spec`.

And whatever name we use should also be used for the filename.

**Comment by lewis6991** [comment]
Shall we just go with `plugspec` for now?

**Comment by ii14** [comment]
`packspec`, `nvimpack`, `npack`, `neopack`

**Comment by mjlbach** [comment]
`packspec` it is :)
